name: 'stripe-mock'
description: 'Starts stripe-mock'

runs:
  using: "composite"
  steps:
    - name: Start stripe-mock
      shell: bash
      run: |
        BETA_ARG=""

        if [ "${{github.base_ref || github.ref_name}}" == "beta" ]; then
          BETA_ARG="-beta"
        fi

        docker run -d -p 12111-12112:12111-12112 stripe/stripe-mock $BETA_ARG && sleep 5

