name: 'Notify Release'
description: 'Sends a slack notification when release succeeds or fails'
inputs:
  bot_token:
    description: 'Slack bot token'
    required: true
    
runs:
  using: "composite"
  steps:
    - uses: stripe/openapi/actions/notify-slack@master
      with:
        bot_token: ${{ inputs.bot_token }}
        action: Releasing ${{ github.repository }} ${{ github.ref_name }}
        send_on_success: true
        send_on_cancelled: true
